#!/bin/bash
# =============================================================
#  deploy.sh  blue | green
#  Auto-generated by VCS for project: {{PROJECT_NAME}}
#  DO NOT manually edit the "修改" block — managed by VCS
#
#  blue  → 部署正式線（同步 green 版本後啟動）
#  green → 部署備援線（直接啟動）
#  回傳碼：
#          0 = 健康檢查成功
#          1 = 健康檢查失敗
# =============================================================
TARGET=$1   # blue | green

# ── 從 config.sh 讀取配置 ─────────────────────────────────────
CONFIG_FILE="/opt/vcs/tools/{{SCRIPT_NAME}}/config.sh"
[[ ! -f "$CONFIG_FILE" ]] && { echo "❌ Config not found: $CONFIG_FILE"; exit 1; }
source "$CONFIG_FILE"

BASE_PATH="${PROD_DEPLOY_BASE}"
SCRIPT_PATH="${BASE_PATH}/script"
ENV_FILE="${BASE_PATH}/.env"
SWITCH_TRAFFIC_SCRIPT="switch_traffic.sh"

BLUE_PORT="${PROD_BLUE_CHECK_PORTS[0]}"
GREEN_PORT="${PROD_GREEN_CHECK_PORTS[0]}"
HEALTH_HOST="${PROD_HEALTH_HOST}"
HEALTH_SCHEME="${PROD_HEALTH_SCHEME:-http}"
HEALTH_PATH="${PROD_HEALTH_PATH:-/}"

PROJECT_NAME="{{PROJECT_NAME}}"
SERVICE_BLUE="${PROJECT_NAME}-blue"
SERVICE_GREEN="${PROJECT_NAME}-green"
# ─────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: deploy.sh [blue|green]
  blue  = 部署正式線
  green = 部署備援線
EOF
}

if [[ "$TARGET" != "blue" && "$TARGET" != "green" ]]; then
    usage; exit 99
fi

# 讀取 .env 版本
BLUE_VERSION=$(grep '^BLUE_VERSION=' "$ENV_FILE" | cut -d '=' -f2)
GREEN_VERSION=$(grep '^GREEN_VERSION=' "$ENV_FILE" | cut -d '=' -f2)
echo "🔵 Blue 版本:  ${BLUE_VERSION}"
echo "🟢 Green 版本: ${GREEN_VERSION}"

# ---------------------------------------------------------
# 部署 BLUE 正式線
# ---------------------------------------------------------
if [[ "$TARGET" == "blue" ]]; then
    # 同步版本
    if [ "$BLUE_VERSION" != "$GREEN_VERSION" ]; then
        echo "🔁 將 BLUE 版本升級與 GREEN 一致"
        sudo sed -i "s|BLUE_VERSION=.*|BLUE_VERSION=${GREEN_VERSION}|g" "$ENV_FILE"
    else
        echo "✔️  BLUE 版本已與 GREEN 相同，跳過同步"
    fi

    cd "$BASE_PATH"
    sudo rm -rf "${BASE_PATH}/${TARGET}/webapp"
    echo "🔃 重啟 BLUE (${SERVICE_BLUE})..."
    docker compose up -d --force-recreate ${SERVICE_BLUE}
    sleep 2

    echo "🔁 將 Header 流量切至 BLUE"
    [[ -f "${SCRIPT_PATH}/${SWITCH_TRAFFIC_SCRIPT}" ]] && "${SCRIPT_PATH}/${SWITCH_TRAFFIC_SCRIPT}" blue header

    HEALTH_URL="${HEALTH_SCHEME}://localhost:${BLUE_PORT}${HEALTH_PATH}"
fi

# ---------------------------------------------------------
# 部署 GREEN 備援線
# ---------------------------------------------------------
if [[ "$TARGET" == "green" ]]; then
    cd "$BASE_PATH"
    sudo rm -rf "${BASE_PATH}/${TARGET}/webapp"
    echo "🔃 重啟 GREEN (${SERVICE_GREEN})..."
    docker compose up -d --force-recreate ${SERVICE_GREEN}
    sleep 2

    echo "🔁 將 Header 流量切至 GREEN"
    [[ -f "${SCRIPT_PATH}/${SWITCH_TRAFFIC_SCRIPT}" ]] && "${SCRIPT_PATH}/${SWITCH_TRAFFIC_SCRIPT}" green header

    HEALTH_URL="${HEALTH_SCHEME}://localhost:${GREEN_PORT}${HEALTH_PATH}"
fi

# ---------------------------------------------------------
# 健康檢查
# ---------------------------------------------------------
echo "🩺 Health Check: ${HEALTH_URL}  (HOST: ${HEALTH_HOST})"
for i in {1..5}; do
    HTTP_STATUS=$(curl -sk -o /dev/null -w "%{http_code}" "${HEALTH_URL}" -H "HOST: ${HEALTH_HOST}")
    echo "   嘗試 ${i}/5 → ${HTTP_STATUS}"
    [[ "$HTTP_STATUS" == "200" ]] && { echo "✅ 健康檢查通過"; exit 0; }
    sleep 3
done
echo "❌ 健康檢查失敗 (最後 HTTP Status: ${HTTP_STATUS})"
exit 1
