#!/bin/bash
# =============================================================
#  rollback.sh
#  Auto-generated by VCS for project: {{PROJECT_NAME}}
#  Green 測試失敗 / 人工 Abort / Timeout → 回復版本
#    1. 流量切回 Blue
#    2. 將 GREEN 版本同步成 BLUE 版本
#    3. 重啟 Green 容器
# =============================================================

# ── 從 config.sh 讀取配置 ─────────────────────────────────────
CONFIG_FILE="/opt/vcs/tools/{{SCRIPT_NAME}}/config.sh"
[[ ! -f "$CONFIG_FILE" ]] && { echo "❌ Config not found: $CONFIG_FILE"; exit 1; }
source "$CONFIG_FILE"

PROJECT_NAME="{{PROJECT_NAME}}"
BASE_PATH="${PROD_DEPLOY_BASE}"
GREEN_SERVICE="${PROJECT_NAME}-green"
SCRIPT_PATH="${BASE_PATH}/script"
ENV_FILE="${BASE_PATH}/.env"
SWITCH_TRAFFIC_SCRIPT="switch_traffic.sh"
# ─────────────────────────────────────────────────────────────

echo "🔍 開始執行 rollback"

[[ ! -f "$ENV_FILE" ]] && { echo "❌ 找不到 ${ENV_FILE}，無法 rollback"; exit 1; }

BLUE_VERSION=$(grep '^BLUE_VERSION=' "$ENV_FILE" | cut -d '=' -f2)
GREEN_VERSION=$(grep '^GREEN_VERSION=' "$ENV_FILE" | cut -d '=' -f2)
echo "🔵 Blue 版本:  ${BLUE_VERSION}"
echo "🟢 Green 版本: ${GREEN_VERSION}"

# 1. 流量切回 Blue
echo "🔁 流量切回 BLUE"
[[ -f "${SCRIPT_PATH}/${SWITCH_TRAFFIC_SCRIPT}" ]] && "${SCRIPT_PATH}/${SWITCH_TRAFFIC_SCRIPT}" blue

# 2. Green 版本同步 Blue
if [ "$BLUE_VERSION" != "$GREEN_VERSION" ]; then
    echo "🔁 將 GREEN 版本恢復成與 BLUE 一致 → ${BLUE_VERSION}"
    sed -i "s|GREEN_VERSION=.*|GREEN_VERSION=${BLUE_VERSION}|g" "$ENV_FILE"
else
    echo "✔️  GREEN 版本已與 BLUE 相同，跳過同步"
fi

# 3. 重啟 Green
echo "🔃 重啟 Green (${GREEN_SERVICE})..."
cd "$BASE_PATH"
docker compose up -d ${GREEN_SERVICE}
sleep 3

echo "🎯 rollback 完成"
echo "🔵 正式線：Blue  ($BLUE_VERSION)"
echo "🟢 備援線：Green (已重置為 $BLUE_VERSION)"
exit 0
