#!/bin/bash
# =============================================================
#  switch_traffic.sh    blue | green [header]
#  Auto-generated by VCS for project: {{PROJECT_NAME}}
#
#  blue              → 將流量切至 BLUE（正式）
#  green             → 將流量切至 GREEN（備援）
#  blue  header      → 只切 header 測試流量至 BLUE
#  green header      → 只切 header 測試流量至 GREEN
#  回傳碼：
#          0  = 成功
#          10 = 跳過（已在此線）
#          1  = 失敗
# =============================================================
TARGET=$1       # blue | green
HEADER_MODE=$2  # header | 空值（正式流量）

# ── 從 config.sh 讀取配置 ─────────────────────────────────────
CONFIG_FILE="/opt/vcs/tools/{{SCRIPT_NAME}}/config.sh"
[[ ! -f "$CONFIG_FILE" ]] && { echo "❌ Config not found: $CONFIG_FILE"; exit 1; }
source "$CONFIG_FILE"

CONF="${PROD_NGINX_CONF}"
BLUE_PORT="${PROD_BLUE_CHECK_PORTS[0]}"
GREEN_PORT="${PROD_GREEN_CHECK_PORTS[0]}"
LIVE_UPSTREAM="${PROD_LIVE_UPSTREAM}"
HEADER_UPSTREAM="${PROD_HEADER_UPSTREAM}"
# ─────────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: switch_traffic.sh [blue|green] [header]
  參數1 = blue | green  (必填)
  參數2 = header        (選填，只切 header 測試流量)
EOF
}

if [[ "$TARGET" != "blue" && "$TARGET" != "green" ]]; then
    usage; exit 99
fi

# 決定 active / down port
[[ "$TARGET" == "blue" ]] && ACTIVE=$BLUE_PORT || ACTIVE=$GREEN_PORT
[[ "$TARGET" == "blue" ]] && DOWN=$GREEN_PORT  || DOWN=$BLUE_PORT

# 決定要切換的 upstream block
if [[ "$HEADER_MODE" == "header" ]]; then
    TRAFFIC_LABEL="header"
    BLOCKS=("${HEADER_UPSTREAM}")
else
    TRAFFIC_LABEL="正式"
    BLOCKS=("${LIVE_UPSTREAM}")
fi

# 已在此線則跳過
BLOCK_TO_CHECK="${BLOCKS[0]}"
if sudo sed -n "/upstream[[:space:]]\+${BLOCK_TO_CHECK}[[:space:]]*{/,/}/p" "$CONF" \
   | grep -q "server 127.0.0.1:${ACTIVE}[[:space:]]*;"; then
    echo "[SKIP] ${TRAFFIC_LABEL} 流量已在 ${TARGET^^}，無須切換"
    exit 10
fi

# 執行 upstream 切換
for block in "${BLOCKS[@]}"; do
    sudo sed -i "/upstream[[:space:]]\+${block}[[:space:]]*{/,/}/ {
        s|server 127.0.0.1:${DOWN}[[:space:]]*;|server 127.0.0.1:${DOWN} down;|;
        s|server 127.0.0.1:${ACTIVE}[[:space:]]*down;|server 127.0.0.1:${ACTIVE};|;
    }" "$CONF"
done

if sudo nginx -t 2>/dev/null; then
    sudo nginx -s reload
    echo "[OK] ${TRAFFIC_LABEL} 流量切換至 ${TARGET^^} (port: ${ACTIVE})"
    exit 0
else
    echo "[ERROR] Nginx config test failed — 請手動確認 ${CONF}"
    exit 1
fi
